feat: added tooltip to display full cumulative funding value and updated funding payment display to display numbers greater than 0.0001
GooseFX1/gfx-web-app pull request #840
Opened 2024-01-15 16:00 UTC by Clish254

## Description

## How has this been tested?

## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] The related ClickUp task has been linked to this PR
- [ ] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

## Screenshots or Loom Video (optional):

2024-01-17 17:33 UTC, deadeagle63 requested changes

2024-01-17 17:33 UTC, deadeagle63 commented on src/pages/Account/components/FundingHistory.tsx
> +            <div className="tooltip">
We have a Tooltip component already, should we use that instead?

2024-01-17 17:33 UTC, deadeagle63 commented on src/pages/Account/components/Mobile/FundingHistory.tsx
> +            <div className="tooltip">
Same as above.

2024-01-17 17:50 UTC, Clish254 commented on src/pages/Account/components/FundingHistory.tsx
> +            <div className="tooltip">
> We have a Tooltip component already, should we use that instead?

I think we could but that one has an info icon and it takes text that is supposed to be a description but for this feature it's just a tooltip displayed when the cumulative funding number is hovered on to display all the decimal places.

2024-01-17 18:44 UTC, deadeagle63 commented on src/pages/Account/components/FundingHistory.tsx
> +            <div className="tooltip">
The tooltip has a built in prop to remove the icon. I believe it is infoIcon (boolean which defaults to true)

2024-01-19 16:14 UTC, walt-1 commented on src/pages/Account/components/FundingHistory.tsx
> +            <div className="tooltip">
yes, and feel free to adjust the component to fit the usecase. there will likely be other similar use cases that could benefit from the update

2024-01-20 17:59 UTC, Clish254 commented on src/pages/Account/components/FundingHistory.tsx
> +            <div className="tooltip">
Managed to use title and children props to fit this usecase, i've pushed the commit to this pr.

2024-01-22 13:32 UTC, deadeagle63 approved these changes

2024-01-26 21:48 UTC, walt-1 approved these changes

2024-01-26 21:51 UTC, merged