Adds changes to georestriction flow to by pass hard coded wallets
GooseFX1/gfx-web-app pull request #901
Opened 2024-04-23 14:43 UTC by Shashank729

Whitelist Asymmetric Wallet

## Description

## How has this been tested?

## Types of changes

- [ ] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] The related ClickUp task has been linked to this PR
- [ ] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

## Screenshots or Loom Video (optional):

2024-04-24 04:57 UTC, AlexOfc requested changes

2024-04-24 04:57 UTC, AlexOfc commented on src/context/settings.tsx
> +    if (curEnv === ENVS.PROD || curEnv === ENVS.DEV) {
That line means that 2 of 3 modes use this feature. Does it really make sense to ignore staging?

Maybe this line is not needed anymore?

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/Connect.tsx
> +    return (
long ternaries are hard to read and maintain.

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/Connect.tsx
> +  const [geoBlocked, setGeoBlocked] = useState<boolean>(false)
boolean generic not needed here. Ts is smart enough to set it by its own

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/Connect.tsx
> +  // useEffect(() => {
Does these comments are needed?

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/Connect.tsx
> +            onClick={() => !connected && handleConnect()}
This should be in useCallback to memoize the function

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/Connect.tsx
> +                  alt={`${wallet?.adapter?.name}_icon`}
Here you do optional chaining 2 times, it transpiles to long checks. You can do all checks in separate variable through destructuring

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/georestrictedModal.tsx
> +  const Content = useMemo(
It should be in separate component, there is to need to make this component bulky

2024-04-24 04:57 UTC, AlexOfc commented on src/layouts/georestrictedModal.tsx
> +  const { mode } = useDarkMode()
Several days ago there were change where isDarkMode passed. It looks more organic. Because we have only two modes

2024-04-24 04:57 UTC, AlexOfc commented on src/pages/FarmV3/FarmTableComponents/FarmTableBalanceItem.tsx
>    const maxDisabled = modeOfOperation === ModeOfOperation.DEPOSIT ? !canDeposit : !canWithdraw
These lines are similar. Why does it need to keep them together?

2024-04-24 04:57 UTC, AlexOfc commented on src/pages/FarmV3/FarmTableComponents/FarmTableBalanceItem.tsx
> +  console.log('userDepositedAmount', userDepositedAmount)
does it really need to keep console log?

2024-04-24 04:57 UTC, AlexOfc commented on src/pages/FarmV3/FarmTableComponents/FarmTableBalanceItem.tsx
> +  //BN.div(2)
This comment is hard to understand

2024-04-24 04:57 UTC, AlexOfc commented on src/pages/FarmV3/FarmTableComponents/FarmTableBalanceItem.tsx
> +  //userDepositedAmount?.lte(new BN(withdrawAmount)
I got What this comment means, but cannot get why it is here. Code is quite clear.

2024-04-26 18:45 UTC, walt-1 commented
@AlexOfc - Thank you for your feedback. We have reviewed and made the necessary changes. If you would like to create a separate branch with changes and recommendations, that will be more helpful that associating them with current pull requests that are targeting specific changes. Thank you

2024-04-26 18:45 UTC, merged