New Transaction Builder/sender
GooseFX1/gfx-web-app pull request #918
Opened 2024-05-13 18:00 UTC by deadeagle63

Feature/new txns

## Description

## How has this been tested?

## Types of changes

- [x] Technical Debt (non-breaking change which removes unused code/assets)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] The related ClickUp task has been linked to this PR
- [ ] The person creating the pull request is listed in "Assignees"
- [ ] Change requires updated documentation

## Screenshots or Loom Video (optional):

2024-05-17 10:52 UTC, AlexOfc requested changes

2024-05-17 10:52 UTC, AlexOfc commented on src/hooks/useTransaction.tsx
> +    }?: {
You have same type on line 47, can u move this copy paste to separate type variable?

2024-05-17 10:52 UTC, AlexOfc commented on src/hooks/useTransaction.tsx
> +  const createTransaction = useCallback(
do u need this method? it is not used anywhere

2024-05-20 18:34 UTC, deadeagle63 commented on src/hooks/useTransaction.tsx
> +    }?: {
Segmented out.

2024-05-20 18:34 UTC, deadeagle63 commented on src/hooks/useTransaction.tsx
> +  const createTransaction = useCallback(
Added as an additional optional builder if someone doesn't want the builder but just the txn for example

2024-05-21 22:08 UTC, walt-1 approved these changes

2024-05-21 22:09 UTC, merged